//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ninja_Simulator.Configuration
{
    public sealed class Inventory
    {
        private static InventorySection _config;

        static Inventory()
        {
            _config = ((InventorySection)(System.Configuration.ConfigurationManager.GetSection("Inventory")));
        }

        private Inventory()
        {
        }

        public static InventorySection Config
        {
            get { return _config; }
        }
    }

    public abstract class Item : System.Configuration.ConfigurationElement
    {
        [System.Configuration.ConfigurationProperty("name", IsRequired = true)]
        public string Name
        {
            get { return ((string)(this["name"])); }
            set { this["name"] = value; }
        }

        [System.Configuration.ConfigurationProperty("dex", IsRequired = true)]
        public long Dex
        {
            get { return ((long)(this["dex"])); }
            set { this["dex"] = value; }
        }

        [System.Configuration.ConfigurationProperty("acc", IsRequired = true)]
        public long Acc
        {
            get { return ((long)(this["acc"])); }
            set { this["acc"] = value; }
        }

        [System.Configuration.ConfigurationProperty("crt", IsRequired = true)]
        public long Crt
        {
            get { return ((long)(this["crt"])); }
            set { this["crt"] = value; }
        }

        [System.Configuration.ConfigurationProperty("det", IsRequired = true)]
        public long Det
        {
            get { return ((long)(this["det"])); }
            set { this["det"] = value; }
        }

        [System.Configuration.ConfigurationProperty("sks", IsRequired = true)]
        public long Sks
        {
            get { return ((long)(this["sks"])); }
            set { this["sks"] = value; }
        }
    }

    public sealed partial class InventorySection : System.Configuration.ConfigurationSection
    {

        [System.Configuration.ConfigurationProperty("MainHand")]
        [System.Configuration.ConfigurationCollection(typeof(MainHandElementCollection.ItemElement),
            AddItemName = "item")]
        public MainHandElementCollection MainHand
        {
            get { return ((MainHandElementCollection)(this["MainHand"])); }
        }

        [System.Configuration.ConfigurationProperty("Head")]
        [System.Configuration.ConfigurationCollection(typeof(HeadElementCollection.ItemElement), AddItemName = "item")]
        public HeadElementCollection Head
        {
            get { return ((HeadElementCollection)(this["Head"])); }
        }

        [System.Configuration.ConfigurationProperty("Body")]
        [System.Configuration.ConfigurationCollection(typeof(BodyElementCollection.ItemElement), AddItemName = "item")]
        public BodyElementCollection Body
        {
            get { return ((BodyElementCollection)(this["Body"])); }
        }

        [System.Configuration.ConfigurationProperty("Hands")]
        [System.Configuration.ConfigurationCollection(typeof(HandsElementCollection.ItemElement), AddItemName = "item")
        ]
        public HandsElementCollection Hands
        {
            get { return ((HandsElementCollection)(this["Hands"])); }
        }

        [System.Configuration.ConfigurationProperty("Waist")]
        [System.Configuration.ConfigurationCollection(typeof(WaistElementCollection.ItemElement), AddItemName = "item")
        ]
        public WaistElementCollection Waist
        {
            get { return ((WaistElementCollection)(this["Waist"])); }
        }

        [System.Configuration.ConfigurationProperty("Legs")]
        [System.Configuration.ConfigurationCollection(typeof(LegsElementCollection.ItemElement), AddItemName = "item")]
        public LegsElementCollection Legs
        {
            get { return ((LegsElementCollection)(this["Legs"])); }
        }

        [System.Configuration.ConfigurationProperty("Feet")]
        [System.Configuration.ConfigurationCollection(typeof(FeetElementCollection.ItemElement), AddItemName = "item")]
        public FeetElementCollection Feet
        {
            get { return ((FeetElementCollection)(this["Feet"])); }
        }

        [System.Configuration.ConfigurationProperty("OffHand")]
        public OffHandElement OffHand
        {
            get { return ((OffHandElement)(this["OffHand"])); }
        }

        [System.Configuration.ConfigurationProperty("Neck")]
        [System.Configuration.ConfigurationCollection(typeof(NeckElementCollection.ItemElement), AddItemName = "item")]
        public NeckElementCollection Neck
        {
            get { return ((NeckElementCollection)(this["Neck"])); }
        }

        [System.Configuration.ConfigurationProperty("Ears")]
        [System.Configuration.ConfigurationCollection(typeof(EarsElementCollection.ItemElement), AddItemName = "item")]
        public EarsElementCollection Ears
        {
            get { return ((EarsElementCollection)(this["Ears"])); }
        }

        [System.Configuration.ConfigurationProperty("Wrists")]
        [System.Configuration.ConfigurationCollection(typeof(WristsElementCollection.ItemElement), AddItemName = "item"
            )]
        public WristsElementCollection Wrists
        {
            get { return ((WristsElementCollection)(this["Wrists"])); }
        }

        [System.Configuration.ConfigurationProperty("LeftRing")]
        [System.Configuration.ConfigurationCollection(typeof(LeftRingElementCollection.ItemElement),
            AddItemName = "item")]
        public LeftRingElementCollection LeftRing
        {
            get { return ((LeftRingElementCollection)(this["LeftRing"])); }
        }

        [System.Configuration.ConfigurationProperty("RightRing")]
        [System.Configuration.ConfigurationCollection(typeof(RightRingElementCollection.ItemElement),
            AddItemName = "item")]
        public RightRingElementCollection RightRing
        {
            get { return ((RightRingElementCollection)(this["RightRing"])); }
        }

        [System.Configuration.ConfigurationProperty("Food")]
        [System.Configuration.ConfigurationCollection(typeof(FoodElementCollection.ItemElement), AddItemName = "item")]
        public FoodElementCollection Food
        {
            get { return ((FoodElementCollection)(this["Food"])); }
        }

        public sealed partial class MainHandElementCollection : System.Configuration.ConfigurationElementCollection
        {
            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
                [System.Configuration.ConfigurationProperty("wd", IsRequired = true)]
                public double Wd
                {
                    get { return ((double)(this["wd"])); }
                    set { this["wd"] = value; }
                }

                [System.Configuration.ConfigurationProperty("aa", IsRequired = true)]
                public double Aa
                {
                    get { return ((double)(this["aa"])); }
                    set { this["aa"] = value; }
                }

                [System.Configuration.ConfigurationProperty("delay", IsRequired = true)]
                public double Delay
                {
                    get { return ((double)(this["delay"])); }
                    set { this["delay"] = value; }
                }
            }
        }

        public sealed partial class HeadElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class BodyElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class HandsElementCollection : System.Configuration.ConfigurationElementCollection
        {
            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class WaistElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class LegsElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class FeetElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class OffHandElement : System.Configuration.ConfigurationElement
        {
            [System.Configuration.ConfigurationProperty("item")]
            public ItemElement Item
            {
                get { return ((ItemElement)(this["item"])); }
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class NeckElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class EarsElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class WristsElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class LeftRingElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class RightRingElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : Item
            {
            }
        }

        public sealed partial class FoodElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ItemElement this[int i]
            {
                get { return ((ItemElement)(this.BaseGet(i))); }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ItemElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ItemElement)(element)).Name;
            }

            public sealed partial class ItemElement : System.Configuration.ConfigurationElement
            {
                [System.Configuration.ConfigurationProperty("name", IsRequired = true)]
                public string Name
                {
                    get { return ((string)(this["name"])); }
                    set { this["name"] = value; }
                }

                [System.Configuration.ConfigurationProperty("accModifier", IsRequired = true)]
                public double AccModifier
                {
                    get { return ((double)(this["accModifier"])); }
                    set { this["accModifier"] = value; }
                }

                [System.Configuration.ConfigurationProperty("maxAccBonus", IsRequired = true)]
                public long MaxAccBonus
                {
                    get { return ((long)(this["maxAccBonus"])); }
                    set { this["maxAccBonus"] = value; }
                }

                [System.Configuration.ConfigurationProperty("crtModifier", IsRequired = true)]
                public double CrtModifier
                {
                    get { return ((double)(this["crtModifier"])); }
                    set { this["crtModifier"] = value; }
                }

                [System.Configuration.ConfigurationProperty("maxCrtBonus", IsRequired = true)]
                public long MaxCrtBonus
                {
                    get { return ((long)(this["maxCrtBonus"])); }
                    set { this["maxCrtBonus"] = value; }
                }

                [System.Configuration.ConfigurationProperty("detModifier", IsRequired = true)]
                public double DetModifier
                {
                    get { return ((double)(this["detModifier"])); }
                    set { this["detModifier"] = value; }
                }

                [System.Configuration.ConfigurationProperty("maxDetBonus", IsRequired = true)]
                public long MaxDetBonus
                {
                    get { return ((long)(this["maxDetBonus"])); }
                    set { this["maxDetBonus"] = value; }
                }

                [System.Configuration.ConfigurationProperty("sksModifier", IsRequired = true)]
                public double SksModifier
                {
                    get { return ((double)(this["sksModifier"])); }
                    set { this["sksModifier"] = value; }
                }

                [System.Configuration.ConfigurationProperty("maxSksBonus", IsRequired = true)]
                public long MaxSksBonus
                {
                    get { return ((long)(this["maxSksBonus"])); }
                    set { this["maxSksBonus"] = value; }
                }
            }
        }
    }
}